import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

import { AccountBar } from "@/components/AccountNav/AccountBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// taiikusai's own Google Analytics measurement ID. (Previously this site
// reused event-week-top's ID; replaced with its own property.)
const GA_MEASUREMENT_ID = "G-FN2J13N4JB";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Google tag (gtag.js) — loaded only when a measurement ID is set and
            this is not a PR preview deployment. IS_PR_PREVIEW is injected at
            runtime by the deploy infra and read here server-side, so it must
            NOT be NEXT_PUBLIC_ (those inline at build time). */}
        {GA_MEASUREMENT_ID && process.env.IS_PR_PREVIEW !== "true" && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${GA_MEASUREMENT_ID}');`}
            </Script>
          </>
        )}
      </head>
      <body className="min-h-full flex flex-col">
        <AccountBar />
        {children}
      </body>
    </html>
  );
}
